# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: alchemistdefi-service
# app and org for use with dashboard.serverless.com
app: alchemistdefi-api
org: alchemistdefi

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn

provider:
  name: aws
  runtime: nodejs12.x
  logRetentionInDays: 30
  environment:
    Provider: "https://bsc-dataseed.binance.org/"
    MistAddress: "0x6f8fe12cc34398d15b7d5a5ba933e550da1d099f"
    AurumAddress: "0x49207BAA3a7332F0716788aa57B088D499bcc104"    
    BurnAddress: "0x000000000000000000000000000000000000dead"    

functions:
  getAurumTotalSupply:
    handler: handler.getAurumTotalSupply
    events:
      - http:
          path: getAurumTotalSupply
          method: get
          cors: true
  getAurumCirculatingSupply:
    handler: handler.getAurumCirculatingSupply
    events:
      - http:
          path: getAurumCirculatingSupply
          method: get
          cors: true
  getMistTotalSupply:
    handler: handler.getMistTotalSupply
    events:
      - http:
          path: getMistTotalSupply
          method: get
          cors: true
  getMistCirculatingSupply:
    handler: handler.getMistCirculatingSupply
    events:
      - http:
          path: getMistCirculatingSupply
          method: get
          cors: true          
  getTVL:
    handler: getTVL.getTVL
    events:
      - http:
          path: getTVL
          method: get
          cors: true
  getMistTVL:
      handler: getTVL.getMistTVL
      events:
        - http:
            path: getMistTVL
            method: get
            cors: true          
  getAurumTVL:
      handler: getTVL.getAurumTVL
      events:
        - http:
            path: getAurumTVL
            method: get
            cors: true          
  getAurumPrice:
      handler: getTVL.getAurumPrice
      events:
        - http:
            path: getAurumPrice
            method: get
            cors: true          
  getMistPrice:
      handler: getTVL.getMistPrice
      events:
        - http:
            path: getMistPrice
            method: get
            cors: true          
